package com.atguigu.ce;

import com.atguigu.boot3.starter.annotation.EnableRobot;
import com.atguigu.boot3.starter.robot.RobotAutoConfiguration;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.Import;


// Generated by https://start.springboot.io
// 优质的 spring/boot/data/security/cloud 框架中文文档尽在 => https://springdoc.cn

/**
 * 自定义starter所有组件包名：com.atguigu.boot3.stater.robot
 * 当前项目的主程序所在包：    com.atguidu.ce
 */
@SpringBootApplication
//@Import(RobotAutoConfiguration.class)
@EnableRobot
public class Boot308CeApplication {

    public static void main(String[] args) {
        SpringApplication.run(Boot308CeApplication.class, args);
    }

}
